name: test ci

on:
  push:
    branches:
      - main

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: setup_python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CRED }}'

      - name: run the script
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          python -s main.py --branch ${{ github.head_ref || github.ref_name }} --sha ${{ github.event.pull_request.head.sha || github.sha }}
